from django import forms
from userMessaging.models import *

class user_messaging_form(forms.ModelForm):

# form used for creating new messages in the system
# Meta makes it so forms can be 'autogenerated'
    class Meta:
        model = Message
        fields = ("subject", "contents", "receiver")